### ISSUE TITLE
Compatibility with non-binder environments

### ISSUE THREAD

**Issue by cparcerisas** [ioos/soundcoop#6]
Right now most of the notebooks (except pypam and environment) do not have the install cell - because mybinder takes care of installing the requirements.txt for us. 
However I think that if people want to run these notebooks somewhere else (Colab, other jupyterlab places) and have no python experience they will not know how to install this. 
I propose that we all add an installing cell to the notebooks with a note saying that it is not necessary to run it when on mybinder? 
Or at least be consistent on all the notebooks. 

Or do you have other proposals? 
@carriecwall @carueda @danellecline @KarinaKh

**Comment by cparcerisas** [comment]
See progress on #8 and #7

**Comment by carriecwall** [comment]
@cparcerisas i was having similar thoughts last night while looking at the notebooks. an installing cell seems crucial for immediate uptake by the community since we aren't truly promoting long-term or wide spread use of mybinder as the sole environment.

**Comment by cparcerisas** [comment]
Great, we can decide if we think is best to have them commented (then default not installing if running without reading) or uncommented and just an explanation saying that no need to run it when using mybinder

**Comment by carriecwall** [comment]
My vote is uncommented with a note but am open to all options/opinions. The dimension reduction/clustering notebook similarly needs a little context for what and how data are read/loaded. If this is annoying, we can ignore my suggestion (which may have been a bad one) to put this content into a separate notebook.

**Comment by cparcerisas** [comment]
Yes indeed! Working on it :) Thanks for the reminder

**Comment by danellecline** [comment]
> I propose that we all add an installing cell to the notebooks with a note saying that it is not necessary to run it when on mybinder? Or at least be consistent on all the notebooks.

That seems fine to me, considering that notebooks can be downloaded, shared, etc. or run in other environments like Colab, where it would be necessary.

**Comment by danellecline** [comment]
I have already added install cells to all the PBP notebooks so we are good to go on that.
